const SUBMIT_USER_LOGIN_DATA = 'SUBMIT_USER_LOGIN_DATA';
const GET_CURRENCIES = 'GET_CURRENCIES';
const ADD_EXPENSE = 'ADD_EXPENSE';
const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
const EDIT_EXPENSE_START = 'EDIT_EXPENSE_START';
const EDIT_EXPENSE_DONE = 'EDIT_EXPENSE_DONE';
const ADD_CSV_TAGS = 'ADD_CSV_TAGS';

export {
  SUBMIT_USER_LOGIN_DATA,
  GET_CURRENCIES,
  ADD_EXPENSE,
  REMOVE_EXPENSE,
  EDIT_EXPENSE_START,
  EDIT_EXPENSE_DONE,
  ADD_CSV_TAGS,
};
